//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingWebApi.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DayInfo()
        {
            this.DiffrentDayInfoes = new HashSet<DiffrentDayInfo>();
        }
    
        public int DayId { get; set; }
        public string Name { get; set; }
        public bool IsOpen { get; set; }
        public string OpenHour { get; set; }
        public string CloseHour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiffrentDayInfo> DiffrentDayInfoes { get; set; }
    }
}
