//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingWebApi.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiffrentDayInfo
    {
        public int DiffDayInfo { get; set; }
        public int DayId { get; set; }
        public bool IsOpen { get; set; }
        public string OpenHour { get; set; }
        public string CloseHour { get; set; }
        public System.DateTime ExactChangeDate { get; set; }
    
        public virtual DayInfo DayInfo { get; set; }
    }
}
