//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingWebApi.Models.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarCosmeticSalonEntities : DbContext
    {
        public CarCosmeticSalonEntities()
            : base("name=CarCosmeticSalonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<BlogImage> BlogImages { get; set; }
        public virtual DbSet<DayInfo> DayInfoes { get; set; }
        public virtual DbSet<DiffrentDayInfo> DiffrentDayInfoes { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrdersInformation> OrdersInformations { get; set; }
        public virtual DbSet<OrdersTemplate> OrdersTemplates { get; set; }
        public virtual DbSet<OrdersTemplateImage> OrdersTemplateImages { get; set; }
        public virtual DbSet<OrdersTemplateInformation> OrdersTemplateInformations { get; set; }
        public virtual DbSet<OrdersTemplateSet> OrdersTemplateSets { get; set; }
        public virtual DbSet<SocialMedia> SocialMedias { get; set; }
        public virtual DbSet<UserImage> UserImages { get; set; }
        public virtual DbSet<UserInformation> UserInformations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
