//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingWebApi.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrdersInformations = new HashSet<OrdersInformation>();
        }
    
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public int CreateOrderUserId { get; set; }
        public int OrderTemplateId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> ExpectedStartOfOrder { get; set; }
        public Nullable<System.DateTime> CompletedOrderDate { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public bool IsOrderCompleted { get; set; }
        public bool IsOrderStarted { get; set; }
    
        public virtual OrdersTemplate OrdersTemplate { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersInformation> OrdersInformations { get; set; }
    }
}
