//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingWebApi.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdersTemplate()
        {
            this.Orders = new HashSet<Order>();
            this.OrdersTemplateInformations = new HashSet<OrdersTemplateInformation>();
            this.OrdersTemplateImages = new HashSet<OrdersTemplateImage>();
            this.OrdersTemplateSets = new HashSet<OrdersTemplateSet>();
        }
    
        public int OrderTemplateId { get; set; }
        public decimal MaxCost { get; set; }
        public decimal MinCost { get; set; }
        public string Name { get; set; }
        public string AdditionalInformation { get; set; }
        public Nullable<System.TimeSpan> ExpectedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersTemplateInformation> OrdersTemplateInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersTemplateImage> OrdersTemplateImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersTemplateSet> OrdersTemplateSets { get; set; }
    }
}
