//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingWebApi.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public int InformationId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string TypeOfInformation { get; set; }
        public string Information { get; set; }
    
        public virtual User User { get; set; }
    }
}
